### ISSUE TITLE
Emote (keyword) no longer do sounds

### ISSUE THREAD

**Issue by Psychoboy** [Psychoboy/PenguinTwitchBot#292]
do LUL in chat no longer does sound

**Comment by Psychoboy** [comment]
```
[06:42:28 ERR] Error running custom command.
System.NotImplementedException: The method or operation is not implemented.
   at DotNetTwitchBot.Bot.Alerts.AlertSound.Generate(String fullConfig) in C:\Source\TestStreamBot\DotNetTwitchBot\Bot\Alerts\AlertSound.cs:line 20
   at DotNetTwitchBot.Bot.Commands.Custom.CustomCommand.<>c__DisplayClass42_0.<PlaySound>b__0() in C:\Source\TestStreamBot\DotNetTwitchBot\Bot\Commands\Custom\CustomCommand.cs:line 587
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DotNetTwitchBot.Bot.Commands.Custom.CustomCommand.PlaySound(CommandEventArgs eventArgs, String args) in C:\Source\TestStreamBot\DotNetTwitchBot\Bot\Commands\Custom\CustomCommand.cs:line 581
   at DotNetTwitchBot.Bot.Commands.Custom.CustomCommand.ProcessTags(CommandEventArgs eventArgs, String originalText) in C:\Source\TestStreamBot\DotNetTwitchBot\Bot\Commands\Custom\CustomCommand.cs:line 476
```
