### ISSUE TITLE
Investigate MySql error

### ISSUE THREAD

**Issue by Psychoboy** [Psychoboy/PenguinTwitchBot#410]
Only happened once so far

```
MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1063
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 425
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 932
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 938
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at DotNetTwitchBot.Bot.Commands.PastyGames.Tax.Elapsed(Object sender, ElapsedEventArgs e) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\PastyGames\Tax.cs:line 68
   at DotNetTwitchBot.Bot.Commands.PastyGames.Tax.Elapsed(Object sender, ElapsedEventArgs e) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\PastyGames\Tax.cs:line 77
[21:52:51 ERR] Error updating chatters.
MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1063
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 425
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 932
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 938
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at DotNetTwitchBot.Bot.Commands.Features.ViewerFeature.UpdateViewer(Viewer viewer) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\Features\ViewerFeature.cs:line 121
   at DotNetTwitchBot.Bot.Commands.Features.ViewerFeature.UpdateViewer(Viewer viewer) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\Features\ViewerFeature.cs:line 131
   at DotNetTwitchBot.Bot.Commands.Features.ViewerFeature.UpdateLastSeen(Viewer viewer) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\Features\ViewerFeature.cs:line 137
   at DotNetTwitchBot.Bot.Commands.Features.ViewerFeature.AddOrUpdateLastSeen(String userId) in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\Features\ViewerFeature.cs:line 114
   at DotNetTwitchBot.Bot.Commands.Features.ViewerFeature.UpdateChatters() in C:\Users\psyco\Source\Repos\PenguinTwitchBot\DotNetTwitchBot\Bot\Commands\Features\ViewerFeature.cs:line 71
```

**Comment by Psychoboy** [comment]
need to monitor to see if it happens again
